fix: add --no-emit-project to `uv export`
This causes an issue with Heroku because by default it will generate the
line `-e .` in the `requirements.txt`, resulting in the following error:

```
ERROR: The editable requirement file:///tmp/build_6e1bb93c (from -r requirements.txt (line 2)) cannot be installed when requiring hashes, because there is no single file to hash.
```